services:
  stats-server:
    build: stat-svc/stat-svc-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  stats-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - stats-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  #ewm-service:
  #  ports:
  #    - "8080:8080"

  #ewm-db:
  #  image: postgres:16.1

volumes:
  stats-data:
